name: Build and deploy Angular app to Azure Web App - restaurant-table-app-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: Upload Angular build output
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: ./dist/restaurant-table-app-ui  # Angular build output folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72B3CAE7DFE04B25AF446808DD618A44 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D025C1DADCD4064AFCEDF9E7501EA23 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B54B4D038343436E993C031BA9BE55A6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurant-table-app-web'
          slot-name: 'Production'
          package: ./dist/restaurant-table-app-ui
